language: android
android: 
sudo: false
components:
- tools
- tools
- platform-tools
- build-tools-25.0.0
- android-23
- extra-google-m2repository
- extra-android-m2repository
jdk:
- oraclejdk8
install:
- android-update-sdk --accept-licenses='android-sdk-license-.+' --components=tools
- android-update-sdk --accept-licenses='android-sdk-license-.+' --components=build-tools-25.0.0
- android-update-sdk --accept-licenses='android-sdk-license-.+' --components=android-23
- android-update-sdk --accept-licenses='android-sdk-license-.+' --components=extra-android-m2repository
- android-update-sdk --accept-licenses='android-sdk-license-.+' --components=extra-google-m2repository
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
script:
- "./gradlew clean build"
deploy:
  provider: releases
  api_key:
    secure: iGlEO10QjsB3dSXQ8NbaG49XjnIlkn6m3NM2aDM4Esk3gXwTCKcZZlWkr/LkYnQERqtxwe4LcA/TECwqw/44OngS9ClaGtmmbx9MDmwg6tfrN0LH5zCHp0hC4xWJMlYVdePNLshYadgSQnbu8vCZPDlvtYNxRy2prrb7OCwkONnU3Q+8ElJGTsajKU3Ls+BOV9in7AuLr0x89CPHTyHs3xYVu9K3srsgIq16Xi687ijSmmS7FPq1v6uzf17/TA06MCt4yTxlJbIzlCqV+9qYHVxXYkeRtp9V+YOZa74Jc0u7Fpg3bx8p4tq8DFuSobWTXE+8MQdwoKc4PZaDacbMA3a2GhDkopfo4tSnLp720dflfb7MKtWCDaaNrIsE4Hm/Tl8Ov65T+2O6mj1OFAT6lgf1z+Nj8nVrpJ64FqhprxAhvKXYMhUii2SRerFTOh2iLZ2ZR3UHOO1sLNChjLvdrbP6USfDl2f4ptO8GJqBx3Qjbpr5YeUgFmz3R+jFWIM/afoJw8uerOkOs2I2NDeWK9dlVEHzSO8quWvkM86ouO613AFyCd24E5pghXuJEqk1B0TY9LqAUa9fYNuD915zsADARkZu7CmsQfQ/vRfK9a9dxQ/3uOMcdnLvDh35NLPdwevMqzsF99K4gf5UOkMqDcrmSrThqsdWTm57ZtXKO1s=
  file: HaskellAnywhereForAndroid/build/outputs/apk/HaskellAnywhereForAndroid*releases*.apk
  on:
    branch: master
    repo: clockvoid/HaskellAnywhereForAndroid
after_success:
- sh set_tags.sh
