language: android

sudo: required

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - tools
  - android-23
  - extra-android-m2repository
  
jdk:
  - oraclejdk8

before_script:
  - echo -n -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"

script:
  - ./gradlew clean build
