language: android

sudo: required

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - tools
  - android-23
  - extra-android-m2repository
  
jdk:
  - oraclejdk8

install:
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=tools

script:
  - ./gradlew clean build
